export const DEFAULT_SPACE_FORMAT = 4;
export const OPEN_BRACE = "{";
export const CLOSE_BRACE = "}";
export const OPEN_PAR = "(";
export const CLOSE_PAR = ")";
export const SPACE = " ";
export const COLON = ":";
export const COMMA = ",";
export const ASYNC = "async";
export const EXPORT = "export";
export const NEWLINE = "\n";
export const FAT_ARROW = "=>";
